const types = {
    GET_DOMAIN_METRICS: 'GET_DOMAIN_METRICS',
    GET_DOMAIN_METRICS_SUCCESS: 'GET_DOMAIN_METRICS_SUCCESS',
    GET_DOMAIN_METRICS_ERROR: 'GET_DOMAIN_METRICS_ERROR',
};

export default types;
